language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - dev

env: DJANGO_SETTINGS_MODULE="PurBeurre_P10.settings.travis"

services:
  - postgresql

script:
  - python3 manage.py test
