language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - dev

env: DJANGO_SETTINGS_MODULE=pur_beurre.settings.travis

services:
  - postgresql

script:
  - python manage.py test
