language: python
python:
  - '3.9'

# addons:
#   firefox: latest

branches:
  only:
    - dev

before_script:
  - pip install -r requirements.txt

env:
  global: 
    - DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

services:
  - postgresql

script:
  - python manage.py test tests