language: python
python:
  - '3.9'

before_script:
  - pip install -r requirements.txt

branches:
  only:
    - dev

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

script:
  - ./manage.py test
